import { NavItem } from "@/types/navigation";
import { Product } from "@/types";

export const BRAND_NAME = "SHIVURA";
export const BRAND_TAGLINE = "Handmade with Purpose";

export const ANNOUNCEMENT_TEXT = "Shivura • Handmade with purpose • Delivered across India";

export const SHOP_CATEGORIES = [
  { label: "All Products", href: "/shop" },
  { label: "Festival Living", href: "/shop/festival-living" },
  { label: "Home Decor", href: "/shop/home-decor" },
  { label: "Lighting", href: "/shop/lighting" },
  { label: "Gifting", href: "/shop/gifting" },
];

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  {
    label: "Shop",
    href: "/shop",
    subItems: SHOP_CATEGORIES,
  },
  { label: "Our Story", href: "/our-story" },
  { label: "Contact Us", href: "/contact" },
  { label: "Blog", href: "/blog" },
  { label: "Cart", href: "/cart" },
];

export const FOOTER_SECTIONS = [
  {
    title: "Explore",
    links: [
      { label: "All Products", href: "/shop" },
      { label: "Festival Living", href: "/shop/festival-living" },
      { label: "Home Decor", href: "/shop/home-decor" },
      { label: "Lighting", href: "/shop/lighting" },
      { label: "Gifting", href: "/shop/gifting" },
    ],
  },
  {
    title: "Customer Care",
    links: [
      { label: "Contact Us", href: "/contact" },
      { label: "Shipping & Delivery", href: "/shipping" },
      { label: "Returns & Exchanges", href: "/returns" },
      { label: "Care Instructions", href: "/care-guide" },
      { label: "FAQs", href: "/faqs" },
    ],
  },
];

export const BRAND_PILLARS = [
  {
    title: "Artisanal Craftsmanship",
    description: "Every piece is thoughtfully designed and created by skilled artisans committed to timeless quality.",
  },
  {
    title: "Conscious Materials",
    description: "Sourced with care for the planet, utilizing natural, organic, and sustainably harvested components.",
  },
  {
    title: "Elevated Simplicity",
    description: "Minimalist aesthetic meets enduring function, designed to elevate your everyday living spaces.",
  },
];

export const BEST_SELLERS_PRODUCTS: Product[] = [
  {
    id: "formula-1-hot-wheels-frame",
    name: "Formula 1 Hot Wheels Car Display Frame (8x12 Inch) | Fi Diecast Wall Art by Shivura",
    href: "/shop/formula-1-hot-wheels-display-frame",
    imageSrc: "/images/Product1.png",
    originalPrice: 499.0,
    price: 299.0,
    isNew: true,
  },
  {
    id: "shivura-240-led-leaf-lights",
    name: "Shivura 240 LED Artificial Leaf String Lights | Warm White Decorative Fairy Lights for Home & Festive Decor",
    href: "/shop/artificial-leaf-string-lights",
    imageSrc: "/images/Product2.png",
    originalPrice: 499.0,
    price: 299.0,
    rating: 5,
    reviewCount: 12,
    isNew: true,
  },
  {
    id: "premium-star-string-lights",
    name: "Premium Star String Fairy Lights for Home Decoration | Warm Yellow LED Lights",
    href: "/shop/star-string-fairy-lights",
    imageSrc: "/images/Product3.png",
    originalPrice: 490.0,
    price: 329.0,
    rating: 5,
    reviewCount: 18,
    isNew: true,
  },
  {
    id: "moroccan-style-lantern-set",
    name: "Moroccan Style Lantern Set | Candle Holder for Home Decor",
    href: "/shop/moroccan-lantern-set",
    imageSrc: "/images/Product4.png",
    originalPrice: 799.0,
    price: 549.0,
    rating: 5,
    reviewCount: 25,
    isNew: true,
  },
];

export const SHOP_SIDEBAR_CATEGORIES = [
  { id: "all", label: "All Products", slug: "all" },
  { id: "artisan-crafts", label: "Artisan Crafts", slug: "artisan-crafts" },
  { id: "bestseller", label: "Bestseller", slug: "bestseller" },
  { id: "clay-pottery", label: "Clay & Pottery", slug: "clay-pottery" },
  { id: "diwali", label: "Diwali", slug: "diwali" },
  { id: "festive-living", label: "Festive Living", slug: "festive-living" },
  { id: "gifting", label: "Gifting", slug: "gifting" },
  { id: "home-decor", label: "Home Decor", slug: "home-decor" },
  { id: "lighting", label: "Lighting", slug: "lighting" },
  { id: "rakhi", label: "Rakhi", slug: "rakhi" },
];

export const ALL_PRODUCTS: Product[] = [
  {
    id: "formula-1-hot-wheels-frame",
    name: "Formula 1 Hot Wheels Car Display Frame (8x12 Inch)",
    href: "/shop/formula-1-hot-wheels-display-frame",
    imageSrc: "/images/Product1.png",
    price: 1299.0,
    rating: 4,
    badge: "Bestseller",
    category: "home-decor",
    categories: ["all", "bestseller", "home-decor", "gifting"],
  },
  {
    id: "shivura-6r-acrylic-wall-photo-frame",
    name: "Shivura 6R Acrylic Wall Photo Frame (6x8 Inch)",
    href: "/shop/shivura-6r-acrylic-wall-photo-frame",
    imageSrc: "/images/frame-6r.jpg",
    price: 899.0,
    rating: 3,
    badge: "New",
    isNew: true,
    category: "home-decor",
    categories: ["all", "home-decor", "artisan-crafts", "gifting"],
  },
  {
    id: "shivura-a4-acrylic-wall-photo-frame",
    name: "Shivura A4 Acrylic Wall Photo Frame for Home",
    href: "/shop/shivura-a4-acrylic-wall-photo-frame",
    imageSrc: "/images/frame-a4.jpg",
    price: 1099.0,
    rating: 5,
    badge: "New",
    isNew: true,
    category: "home-decor",
    categories: ["all", "home-decor", "artisan-crafts"],
  },
  {
    id: "shivura-premium-mauli-kalava-raksha-thread",
    name: "Shivura Premium Mauli Kalava Raksha Thread Set",
    href: "/shop/shivura-premium-mauli-kalava",
    imageSrc: "/images/mauli-kalava.jpg",
    price: 349.0,
    rating: 4,
    badge: "New",
    isNew: true,
    category: "rakhi",
    categories: ["all", "rakhi", "festive-living", "diwali"],
  },
  {
    id: "shivura-premium-blue-om-rakhi",
    name: "Shivura Premium Blue Om Rakhi for Brother with Dairy",
    href: "/shop/shivura-premium-blue-om-rakhi",
    imageSrc: "/images/om-rakhi.jpg",
    price: 399.0,
    rating: 4,
    badge: "New",
    isNew: true,
    category: "rakhi",
    categories: ["all", "rakhi", "gifting", "festive-living"],
  },
  {
    id: "shivura-handmade-terracotta-diya-set",
    name: "Shivura Handmade Terracotta Diya for Diwali | Premium Clay Earthen Oil Lamp",
    href: "/shop/terracotta-diya-set",
    imageSrc: "/images/festive living.png",
    originalPrice: 399.0,
    price: 229.0,
    rating: 5,
    reviewCount: 28,
    badge: "Bestseller",
    category: "festive-living",
    categories: ["all", "bestseller", "clay-pottery", "diwali", "festive-living"],
  },
  {
    id: "shivura-240-led-leaf-lights",
    name: "Shivura 240 LED Artificial Leaf String Lights | Warm White Decorative Fairy Lights for Home & Festive Decor",
    href: "/shop/artificial-leaf-string-lights",
    imageSrc: "/images/Product2.png",
    originalPrice: 499.0,
    price: 299.0,
    rating: 5,
    reviewCount: 12,
    badge: "Bestseller",
    category: "lighting",
    categories: ["all", "bestseller", "lighting", "home-decor"],
  },
  {
    id: "premium-star-string-lights",
    name: "Premium Star String Fairy Lights for Home Decoration | Warm Yellow LED Lights",
    href: "/shop/star-string-fairy-lights",
    imageSrc: "/images/Product3.png",
    originalPrice: 490.0,
    price: 329.0,
    rating: 5,
    reviewCount: 18,
    badge: "New",
    isNew: true,
    category: "lighting",
    categories: ["all", "lighting", "diwali", "festive-living"],
  },
  {
    id: "moroccan-style-lantern-set",
    name: "Moroccan Style Lantern Set | Candle Holder for Home Decor",
    href: "/shop/moroccan-lantern-set",
    imageSrc: "/images/Product4.png",
    originalPrice: 799.0,
    price: 549.0,
    rating: 5,
    reviewCount: 25,
    badge: "Bestseller",
    category: "home-decor",
    categories: ["all", "bestseller", "home-decor", "lighting", "gifting"],
  },
  {
    id: "handcrafted-clay-kulhad-set",
    name: "Shivura Handcrafted Traditional Terracotta Tea Kulhad Set (Set of 6)",
    href: "/shop/handcrafted-clay-kulhad-set",
    imageSrc: "/images/Art1.png",
    originalPrice: 650.0,
    price: 449.0,
    rating: 5,
    reviewCount: 14,
    badge: "New",
    category: "clay-pottery",
    categories: ["all", "clay-pottery", "artisan-crafts", "gifting"],
  },
  {
    id: "madhubani-motif-wall-plate",
    name: "Hand-Painted Madhubani Motif Wall Art Decorative Ceramic Plate",
    href: "/shop/madhubani-wall-plate",
    imageSrc: "/images/Art2.png",
    originalPrice: 1199.0,
    price: 799.0,
    rating: 5,
    reviewCount: 9,
    badge: "New",
    isNew: true,
    category: "artisan-crafts",
    categories: ["all", "artisan-crafts", "home-decor"],
  },
  {
    id: "royal-brass-pooja-thali-set",
    name: "Shivura Royal Brass Pooja Thali Set with Incense & Diya Holder",
    href: "/shop/royal-brass-pooja-thali",
    imageSrc: "/images/Art3.png",
    originalPrice: 2199.0,
    price: 1499.0,
    rating: 5,
    reviewCount: 31,
    badge: "Bestseller",
    category: "festive-living",
    categories: ["all", "bestseller", "diwali", "festive-living", "artisan-crafts"],
  },
  {
    id: "artisanal-jute-macrame-wall-hanging",
    name: "Artisanal Hand-Woven Jute Macrame Boho Wall Hanging Tapestry",
    href: "/shop/jute-macrame-wall-hanging",
    imageSrc: "/images/Hand.png",
    originalPrice: 1299.0,
    price: 899.0,
    rating: 4,
    reviewCount: 16,
    category: "artisan-crafts",
    categories: ["all", "home-decor", "artisan-crafts"],
  },
  {
    id: "festive-gifting-hamper-box",
    name: "Shivura Luxury Festive Gift Box with Scented Soy Candles & Brass Keepsake",
    href: "/shop/festive-gifting-hamper",
    imageSrc: "/images/gifting.png",
    originalPrice: 1699.0,
    price: 1199.0,
    rating: 5,
    reviewCount: 22,
    badge: "Bestseller",
    category: "gifting",
    categories: ["all", "bestseller", "gifting", "festive-living", "diwali"],
  },
  {
    id: "ceramic-aroma-diffuser-lamp",
    name: "Handmade Ceramic Aroma Diffuser & Essential Oil Warm Lamp",
    href: "/shop/ceramic-aroma-diffuser",
    imageSrc: "/images/home decor.png",
    originalPrice: 899.0,
    price: 599.0,
    rating: 5,
    reviewCount: 19,
    category: "clay-pottery",
    categories: ["all", "clay-pottery", "home-decor", "lighting"],
  },
  {
    id: "warm-yellow-rice-lights-festive",
    name: "Warm Yellow LED Rice Fairy String Lights for Home & Festival",
    href: "/shop/warm-yellow-led-rice-fairy-lights",
    imageSrc: "/images/lighting.png",
    originalPrice: 399.0,
    price: 219.0,
    rating: 5,
    reviewCount: 15,
    category: "lighting",
    categories: ["all", "lighting", "diwali", "festive-living"],
  },
  {
    id: "kundan-silk-rakhi-trio-pack",
    name: "Shivura Handcrafted Silk Thread Kundan Rakhi Set with Roli Chawal",
    href: "/shop/kundan-silk-rakhi-pack",
    imageSrc: "/images/om-rakhi.jpg",
    originalPrice: 450.0,
    price: 299.0,
    rating: 5,
    reviewCount: 8,
    badge: "New",
    isNew: true,
    category: "rakhi",
    categories: ["all", "rakhi", "gifting"],
  },
];

export const NEW_ARRIVALS_PRODUCTS: Product[] = ALL_PRODUCTS.filter(
  (p) => p.isNew || p.badge === "New"
).slice(0, 5);



